doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            datetime: Doctrine\DBAL\Types\VarDateTimeType
            datetimez: Doctrine\DBAL\Types\VarDateTimeType
            time: Doctrine\DBAL\Types\VarDateTimeType
            datetime_immutable: Doctrine\DBAL\Types\VarDateTimeImmutableType
            datetimetz_immutable: Doctrine\DBAL\Types\VarDateTimeImmutableType
            time_immutable: Doctrine\DBAL\Types\VarDateTimeImmutableType
            php_decimal: Enraged\Ebenezer\Infrastructure\Doctrine\Type\PhpDecimalType
        platform_service: Enraged\Ebenezer\Infrastructure\Doctrine\PostgreSQLPlatform
            
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Enraged\Ebenezer\Application:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/application'
                prefix: 'Enraged\Ebenezer\Application'
            Enraged\Ebenezer\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/domain'
                prefix: 'Enraged\Ebenezer\Domain'
            Enraged\Ebenezer\Infrastructure:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/infrastructure'
                prefix: 'Enraged\Ebenezer\Infrastructure'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
