# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        
    _instanceof:
        Enraged\Ebenezer\Infrastructure\Doctrine\Type\AbstractEnumType:
            tags: ['ebenezer.doctrine_enum_type']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Enraged\Ebenezer\:
        resource: '../src/Enraged/Ebenezer/'
        exclude:
            - '../src/Enraged/Ebenezer/Infrastructure/Symfony/Kernel.php'
            - '../src/Enraged/Ebenezer/Infrastructure/Symfony/CompilerPass/'
            - '../src/Enraged/Ebenezer/UserInterface/Exception/'
            - '../src/Enraged/Ebenezer/Application/Exception/'
            - '../src/Enraged/Ebenezer/Domain/Exception/'
            - '../src/Enraged/Ebenezer/Infrastructure/Exception/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    Enraged\Ebenezer\CalendarInterface: '@Enraged\Ebenezer\Infrastructure\Calendar\Calendar'
    
    Enraged\Ebenezer\Domain\Asset\AssetInterface: '@Enraged\Ebenezer\Infrastructure\ORM\AssetRepository'

when@dev:
    services:
        
        Enraged\Ebenezer\Infrastructure\Doctrine\Listener\FixPostgreSQLDefaultSchemaListener:
            tags:
                - { name: doctrine.event_listener, event: postGenerateSchema }

when@test:
    services:

        Enraged\Ebenezer\CalendarInterface: '@Enraged\Ebenezer\Infrastructure\Test\Calendar\CalendarStub'
